version: 2
jobs:
  build:
    docker:
      - image: johannr/fem-book-test:latest
    environment:
      MPLBACKEND: "agg"
      ENV_NAME: "fem-book-test"
    steps:
      - checkout
      - run:
          name: Run scripts in src
          command: |
            source activate ${ENV_NAME}
            cd doc/.src/book/src
            ./run_all.sh
      - run:
          name: Run scripts in exer
          command: |
            source activate ${ENV_NAME}
            cd doc/.src/book/exer
            ./run_all.sh
      - run:
          name: Build book
          command: |
            source activate ${ENV_NAME}
            cd doc/.src/book
            ./make.sh
            ./make_html.sh
            mkdir /tmp/artifacts
            cp ../../pub/book/pdf/*.pdf /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
