version: 2
jobs:
  build:
    docker:
      - image: johannr/fem-book-test:latest
    environment:
      MPLBACKEND: "agg"
      ENV_NAME: "fem-book-test"
    steps:
      - checkout
      - run:
          name: Run scripts in src
          command: |
            conda activate ${ENV_NAME}
            cd doc/.src/book/src
            ./run_all.sh
      - run:
          name: Run scripts in exer
          command: |
            conda activate ${ENV_NAME}
            cd doc/.src/book/exer
            ./run_all.sh
      - run:
          name: Build book
          command: |
            conda activate ${ENV_NAME}
            cd doc/.src/book
            #./make.sh
